schema_version: '0.1'
song_ref: neko_funjatta_test_piano_120
format: bootstrap
transport:
  bpm: 120.0
  ppq: 15360
  time_signature: 4/4
tracks:
- id: piano
  name: Piano
  instrument: Acoustic Grand Piano
  channel: 0
  program: 0
notes:
- track: piano
  pitch: 60
  start: 1:1:264
  duration: 0:1:3094
  velocity: 100
- track: piano
  pitch: 62
  start: 1:2:7791
  duration: 0:0:2854
  velocity: 95
- track: piano
  pitch: 64
  start: 1:3:155
  duration: 0:1:2676
  velocity: 104
- track: piano
  pitch: 60
  start: 1:4:7437
  duration: 0:0:2263
  velocity: 85
- track: piano
  pitch: 64
  start: 1:4:14601
  duration: 0:0:11025
  velocity: 93
- track: piano
  pitch: 60
  start: 2:1:14823
  duration: 0:0:13165
  velocity: 95
- track: piano
  pitch: 64
  start: 2:3:294
  duration: 0:1:2983
  velocity: 92
- track: piano
  pitch: 62
  start: 2:4:14690
  duration: 0:1:2645
  velocity: 116
- track: piano
  pitch: 64
  start: 3:2:6827
  duration: 0:0:3241
  velocity: 100
- track: piano
  pitch: 65
  start: 3:2:13714
  duration: 0:0:3069
  velocity: 96
- track: piano
  pitch: 65
  start: 3:3:5518
  duration: 0:0:3180
  velocity: 74
- track: piano
  pitch: 64
  start: 3:3:13488
  duration: 0:0:2466
  velocity: 79
- track: piano
  pitch: 62
  start: 3:4:6128
  duration: 0:0:1630
  velocity: 83
- track: piano
  pitch: 65
  start: 3:4:13556
  duration: 0:2:15043
  velocity: 124
- track: piano
  pitch: 64
  start: 4:4:14083
  duration: 0:1:4490
  velocity: 89
- track: piano
  pitch: 65
  start: 5:2:8095
  duration: 0:0:3118
  velocity: 93
- track: piano
  pitch: 67
  start: 5:3:643
  duration: 0:1:2289
  velocity: 70
- track: piano
  pitch: 69
  start: 5:3:692
  duration: 0:0:4913
  velocity: 74
- track: piano
  pitch: 64
  start: 5:4:6916
  duration: 0:0:2374
  velocity: 83
- track: piano
  pitch: 67
  start: 5:4:14019
  duration: 0:0:12096
  velocity: 90
- track: piano
  pitch: 64
  start: 6:1:14973
  duration: 0:0:11801
  velocity: 96
- track: piano
  pitch: 67
  start: 6:2:14531
  duration: 0:1:8567
  velocity: 73
- track: piano
  pitch: 65
  start: 6:4:14791
  duration: 0:1:2442
  velocity: 94
- track: piano
  pitch: 67
  start: 7:2:7814
  duration: 0:0:2822
  velocity: 80
- track: piano
  pitch: 60
  start: 7:2:14824
  duration: 0:0:2773
  velocity: 96
- track: piano
  pitch: 69
  start: 7:2:15242
  duration: 0:0:2730
  velocity: 96
- track: piano
  pitch: 60
  start: 7:3:5558
  duration: 0:0:2823
  velocity: 91
- track: piano
  pitch: 69
  start: 7:3:6160
  duration: 0:0:3179
  velocity: 94
- track: piano
  pitch: 67
  start: 7:3:13668
  duration: 0:0:3130
  velocity: 81
- track: piano
  pitch: 60
  start: 7:3:13761
  duration: 0:0:3271
  velocity: 89
- track: piano
  pitch: 65
  start: 7:4:4495
  duration: 0:0:3363
  velocity: 84
- track: piano
  pitch: 60
  start: 7:4:14543
  duration: 0:3:7928
  velocity: 112
- track: piano
  pitch: 69
  start: 8:1:130
  duration: 0:3:7123
  velocity: 85
- track: piano
  pitch: 67
  start: 9:1:717
  duration: 0:1:1883
  velocity: 96
- track: piano
  pitch: 60
  start: 9:2:7747
  duration: 0:0:3382
  velocity: 88
- track: piano
  pitch: 62
  start: 9:2:14819
  duration: 0:0:3118
  velocity: 75
- track: piano
  pitch: 64
  start: 9:3:6112
  duration: 0:0:3628
  velocity: 59
- track: piano
  pitch: 65
  start: 9:3:13479
  duration: 0:0:2946
  velocity: 74
- track: piano
  pitch: 67
  start: 9:4:5885
  duration: 0:0:2670
  velocity: 58
- track: piano
  pitch: 60
  start: 9:4:13905
  duration: 0:3:5248
  velocity: 79
- track: piano
  pitch: 62
  start: 9:4:14089
  duration: 0:0:4747
  velocity: 68
- track: piano
  pitch: 69
  start: 9:4:14476
  duration: 0:3:6165
  velocity: 92
- track: piano
  pitch: 69
  start: 11:1:651
  duration: 0:1:3869
  velocity: 89
- track: piano
  pitch: 62
  start: 11:2:7465
  duration: 0:0:3444
  velocity: 73
- track: piano
  pitch: 64
  start: 11:2:14334
  duration: 0:0:2761
  velocity: 76
- track: piano
  pitch: 65
  start: 11:3:5689
  duration: 0:0:2995
  velocity: 77
- track: piano
  pitch: 67
  start: 11:3:12791
  duration: 0:0:2995
  velocity: 65
- track: piano
  pitch: 69
  start: 11:4:5125
  duration: 0:0:3148
  velocity: 44
- track: piano
  pitch: 70
  start: 11:4:14010
  duration: 0:3:4332
  velocity: 119
- track: piano
  pitch: 70
  start: 12:4:13448
  duration: 0:1:3328
  velocity: 80
- track: piano
  pitch: 64
  start: 13:2:6704
  duration: 0:0:3954
  velocity: 64
- track: piano
  pitch: 57
  start: 13:2:13930
  duration: 0:1:6998
  velocity: 87
- track: piano
  pitch: 62
  start: 13:2:14256
  duration: 0:1:6365
  velocity: 95
- track: piano
  pitch: 55
  start: 13:4:14036
  duration: 0:1:5326
  velocity: 71
- track: piano
  pitch: 64
  start: 13:4:14626
  duration: 0:1:4828
  velocity: 84
- track: piano
  pitch: 64
  start: 14:3:411
  duration: 0:1:9687
  velocity: 54
- track: piano
  pitch: 52
  start: 14:3:473
  duration: 0:1:9004
  velocity: 61
- track: piano
  pitch: 67
  start: 14:3:646
  duration: 0:1:10829
  velocity: 51
- track: piano
  pitch: 60
  start: 14:3:848
  duration: 0:1:9526
  velocity: 68
- track: piano
  pitch: 59
  start: 15:1:3777
  duration: 0:3:9233
  velocity: 81
- track: piano
  pitch: 66
  start: 15:1:3839
  duration: 0:3:9712
  velocity: 54
- track: piano
  pitch: 50
  start: 15:1:3869
  duration: 0:3:9946
  velocity: 57
- track: piano
  pitch: 62
  start: 15:1:3869
  duration: 0:3:9528
  velocity: 68
